[package]
name = "sod-server"
version = "0.1.0"
authors = ["austinabell <austinabell8@gmail.com>"]
edition = "2018"

[dependencies]
mongodb = "2.0.0-beta"
tokio = "1.6.1"
serde = "1.0"
warp = "0.3"
pretty_env_logger = "0.4"
futures = "0.3"
thiserror = "1.0"
dotenv = "0.15"